identifier: lez7ebz7o3w4o74b
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: portfolio
homeFolder: >-
  C:\Users\usuario\Desktop\l\learn\portfolio\YP_PortfolioFrontend\PortfolioFrontend
distFolder: ./dist/portfolio
outDir: >-
  C:\Users\usuario\Desktop\l\learn\portfolio\YP_PortfolioFrontend\PortfolioFrontend\dist\portfolio
handle404: ''
allowErrorCollect: false
